import i18n from "i18n-js";
import * as Localization from 'expo-localization'

i18n.translations = {
    en: { 
        quantity: 'Quantity', 
        weight: 'Weight',  
        distance: 'Distance',
        liquid: 'Liquid',
        area: 'Area',
        pound: 'Pounds',
        ton: 'Tons',
        uston: 'US Tons',
        tonne: 'Tonnes',
        foot: 'Feet',
        yard: 'Yards',
        inch: 'Inches',
        mile: 'Miles',
        ounce: 'Ounces',
        pint: 'UK Pints',
        gallon: 'UK Gallons',
        squarefeet: 'Square Foot',
        acre: 'Acres',
        home: 'Home',
        typeOfProduct: 'Type of product',
        typeOfMeasure: 'Measurement type',
        product: 'Product',
        item: 'Item',
        price: 'Price',
        confirm: 'Confirm',
        cancel: 'Cancel',
        update: 'Update',
        remove: 'Remove',
        measure: 'Measure',
        kg: 'Kilograms',
        g: 'Grams',
        mg: 'Miligrams',
        stone: 'Stones',
        km: 'Kilometers'        ,
        m: 'Meters',
        mm: 'Milimeters',
        cm: 'Centimeters',
        yard: 'Yards',
        inch: 'Inches',
        mile: 'Miles',
        nauticmile: 'Nautic Miles',
        feet: 'Feet',
        hectare: 'Hectares',
        acre: 'Acres',
        usgallon: 'US Gallons',
        usquart: 'US Quarts',
        quart: 'UK Quarts',
        uspint: 'US Pints',
        uscup: 'US Cups',
        cup: 'UK Cups',
        cubicmeter: 'Cubic Meters',
        liter: 'Liters',
        ml: 'Mililiters',
        cubicfoot: 'Cubic feet',
        cubicinch: 'Cubic inches',
        squaremeter: 'Square meters',
        squarecm: 'Square centimeters',
        squarekm: 'Square kilometers',
        squarefoot: 'Square feet',
        squareyard: 'Square yards',
        squaremile: 'Square miles',
        squareinch: 'Square inches',
        comparePrice: 'Compare Prices',
        convert: 'Convert',
        value: 'Value',
        from: 'From',
        to: 'To',
        result: 'Result'
    },
    pt: { 
        quantity: 'Quantidade', 
        weight: 'Peso',  
        distance: 'Distância',
        liquid: 'Líquido',
        area: 'Área',
        pound: 'Libras',
        ounce: 'Onças (oz)',
        ton: 'Imperial Tons',
        uston: 'US Tons',
        tonne: 'Toneladas',
        foot: 'Pés',
        yard: 'Jardas',
        inch: 'Polegadas',
        mile: 'Milhas',
        pint: 'UK Pints',
        gallon: 'UK Galões',
        squarefeet: 'Pé quadrado',
        acre: 'Acres',
        home: 'Início',
        typeOfProduct: 'Tipo de produto',
        typeOfMeasure: 'Tipo de medida',
        product: 'Produto',
        item: 'Item',
        price: 'Preço',
        confirm: 'Confirmar',
        cancel: 'Cancelar',
        update: 'Atualizar',
        remove: 'Remover',
        measure: 'Medida',
        kg: 'Kilogramas',
        g: 'Gramas',
        mg: 'Miligramas',
        stone: 'Stones',
        km: 'Kilômetros',
        m: 'Metros',
        mm: 'Milimetros',
        cm: 'Centimetros',
        yard: 'Jardas',
        inch: 'Polegadas',
        mile: 'Milhas',
        nauticmile: 'Milhas Náuticas',
        feet: 'Pés',
        hectare: 'Hectares',
        acre: 'Acres',
        usgallon: 'US galões',
        usquart: 'US quarts',
        quart: 'UK Quarts',
        uspint: 'US Pints',
        uscup: 'US Copos',
        cup: 'UK Copos',
        cubicmeter: 'Metros cúbicos',
        liter: 'Litros',
        ml: 'Mililitros',
        cubicfoot: 'Pés cúbicos',
        cubicinch: 'Polegadas cúbicas',
        squaremeter: 'Metros quadrados',
        squarecm: 'Centímetros quadrados',
        squarekm: 'Kilômetros quadrados',
        squarefoot: 'Pés quadrados',
        squareyard: 'Jardas quadradas',
        squaremile: 'Milhas quadradas',
        squareinch: 'Polegadas quadradas',
        comparePrice: 'Comparar preços',
        convert: 'Converter',
        value: 'Valor',
        from: 'De',
        to: 'Para',
        result: 'Resultado'
    },
    es: { 
        quantity: 'Cantidade', 
        weight: 'Peso',  
        distance: 'Distancia',
        liquid: 'Líquido',
        area: 'Área',
        pound: 'Libras',
        ounce: 'Onzas (Oz)',
        ton: 'Imperial Tons',
        uston: 'US Tons',
        tonne: 'Toneladas',
        foot: 'Pies',
        yard: 'Yardas',
        inch: 'Pulgadas',
        mile: 'Millas',
        pint: 'UK Pintas',
        gallon: 'UK Galón',
        squarefeet: 'Pie cuadrado',
        acre: 'Acres',
        home: 'Comienzo',
        typeOfProduct: 'Tipo de producto',
        typeOfMeasure: 'Tipo de medida',
        product: 'Producto',
        item: 'Item',
        price: 'Precio',
        confirm: 'Confirmar',
        cancel: 'Cancelar',
        update: 'Actualizar',
        remove: 'Eliminar',
        measure: 'Medida',
        kg: 'Kilogramos',
        g: 'Gramos',
        mg: 'Miligramos',
        stone: 'Stones',
        km: 'Kilómetros',
        m: 'Metros',
        mm: 'Milímetros',
        cm: 'Címetros',
        yard: 'Yardas',
        inch: 'Pulgadas',
        mile: 'Millas',
        nauticmile: 'Millas náuticas',
        feet: 'Pies',
        hectare: 'Hectáreas',
        acre: 'Acres',
        usgallon: 'US Galóns',
        usquart: 'US Cuarto',
        quart: 'UK Cuarto',
        uspint: 'US Pintas',
        uscup: 'US Tazas',
        cup: 'UK Tazas',
        cubicmeter: 'Metros cúbicos',
        liter: 'Litros',
        ml: 'Mililitros',
        cubicfoot: 'Pies cúbicos',
        cubicinch: 'Pulgadas cúbicas',
        squaremeter: 'Metros cuadrados',
        squarecm: 'Centímetros cuadrados',
        squarekm: 'Kilómetros cuadrados',
        squarefoot: 'Pies cuadrados',
        squareyard: 'Yardas cuadradas',
        squaremile: 'Millas cuadradas',
        squareinch: 'Pulgadas cuadradas',
        comparePrice: 'Comparar precios',
        convert: 'Convertir',
        value: 'Valor',
        from: 'De',
        to: 'a',
        result: 'Resultado'
    },
}

i18n.locale = Localization.locale
i18n.fallbacks = true

export default i18n